### PR TITLE
bug fixes and some new features

### PR DESCRIPTION
**Pull request by rnijenhu**
had to fix some bugs for my python version 

meanwhile I added some new stuff as well (see changelog.md)

you can check : http://www.tenijenhuis.net/films/ for a live demo, but not all new stuff is enabled there

greetings Rob

### CODE REVIEW

**Comment by GAZ082** [comment]
Thank you man for sharing! I'll check it out later today and merge the code!

**Comment by GAZ082** [comment]
1. Why did you move the css to the main html file? I find that not elegant.
2. I may add a new icon for new movies instead of making them red.
3. I dont like the added title, category and year under the posters, it's not elegant and ruins the aesthetics. Did you do that for anything in particular?
4. There is a bunch of posters added that should not be there.

Waiting your comments. Thanks!

**Comment by rnijenhu** [comment]
1. it's optional by the 'cssinline' setting. This is for performance and organizational reason. But this differs by the way it's used. For me this is an add-on for my website and I don't like to have a bunch of files hanging around. And also performance, in combination with a long expire setting for the HTML page I try to reduce traffic and hits. Had even thoughts about including the images as well, as a result I got a single HTML file with all the info/data, but than again you will lose performance (file gets large and with separate files you only receive the changes/parts, the images are pretty much static). I think the default should be external (indeed more elegant), and the cssinline is for specific situations.  
2. Yep thought about it. The current "watched" image expresses more a "new" movie, I needed to think (more) about this, and had to search for a new image..;)  wanted to go forward with the coding and made it a config issue. You can just change the template in the config and the css to change this. Reduces the discussion to: what should be the default behaviour/config
3. yep I did, cause I like foreign movies as well. And in the Netherlands we watch movies in their original language with subtitles. This means I got a cover that I cannot read (chinees for example), and for the slide info window I need to click the cover first to see more info (which is in the language of kodi). That's not nice and time consuming when you search a movie you like to watch. So I needed more info, in my preferred language, directly visible. This is also a config issue: what would be the default setting
4. oeps, yeah my first github pull request. sorry for that, will remove them 

My general thoughts:
1. Everything boils down to: what is the default behaviour/config settings
2. Maybe provide more samples/templates in the config to show the different results
3. We need to harden/improve the css cause I doubt it's flexible enough to do this. This is an open point (see changelog). For example, when you remove the title/category the movie (div) box gets smaller, the overlay will (probably) stay the old size.  

Hopefully you liked the changes in general (changes are not always improvements ;)

**Comment by GAZ082** [comment]
Hey Rob. These changes are reflected in your current live demo? Because I like them more than i saw months ago and would merge.

**Comment by rnijenhu** [comment]
It's the same code, only different configuration (config.py). The active one (config in github) is the one I used for coding/testing. Maybe I should change this to the one I use in the live demo.

**Comment by GAZ082** [comment]
Yeah man, can you? Will merge as soon as you change the config. Danke!

**Comment by rnijenhu** [comment]
reading your previous comments again I made some additional changes 
point 1: will change the default inline setting to disabled as well. It's only typical for my situation. 
point 2: implemented a ribbon and made it default
point 3: it's removed but can be enabled in the config  

see next pull request

**Comment by GAZ082** [comment]
It's in! Hope it works! :dancer:

**Pull request merged**
